CREATE TABLE `web`.`todolist` (
  `id` INT NOT NULL,
  `info` VARCHAR(255) NULL,
  `state` INT(11) NOT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

ALTER TABLE `web`.`todolist` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

